version: "3.8"
services:
  app:
    build: .
    # Map container port 3000 to host port 3000
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
    restart: unless-stopped
    volumes:
      - ./data:/app/data
